name:                bgp-fact-check
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/bgp-fact-check#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers
  - mtl
  - safe
  - pretty-simple
  - lens
  - random
  - array

executables:
  bgp-fact-check:
    source-dirs:      src
    main:             Main.hs
